[tool.poetry]
name = "textclean"
version = "0.1.0"
description = "process and clean text datasets interactively"
authors = ["Will Epperson <willepp@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
