[tool.poetry]
name = "textclean"
version = "0.1.0"
description = "process and clean text datasets interactively"
authors = ["Will Epperson <willepp@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
pandas = "^2.1.0"
sentence-transformers = "^2.2.2"
pyod = "^1.1.0"
torch = "^2.1.1"
fastapi = "^0.104.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
