import type { DatasetInfo } from "./types";

// TODO: in the future this will be stored server side and fetched

export const datasets: { [key: string]: DatasetInfo } = {
  dolly: {
    name: "dolly",
    filename: "dolly15k.parquet",
    metadata: {
      text_columns: ["instruction", "context", "response"],
      other_columns: ["category"],
      text_meta_columns: {
        instruction: [
          "instruction_text_length",
          "instruction_num_words",
          "instruction_max_word_length",
          "instruction_avg_word_length",
          "instruction_perc_special_chars",
          "instruction_dist_from_mean_embed_all-mpnet-base-v2",
          "instruction_outlier_score_ECOD_all-mpnet-base-v2",
          "instruction_outlier_score_IForest_all-mpnet-base-v2",
          "instruction_dist_from_mean_embed_all-MiniLM-L6-v2",
          "instruction_outlier_score_ECOD_all-MiniLM-L6-v2",
          "instruction_outlier_score_IForest_all-MiniLM-L6-v2",
          "instruction_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "instruction_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "instruction_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],
        context: [
          "context_text_length",
          "context_num_words",
          "context_max_word_length",
          "context_avg_word_length",
          "context_perc_special_chars",
          "context_dist_from_mean_embed_all-mpnet-base-v2",
          "context_outlier_score_ECOD_all-mpnet-base-v2",
          "context_outlier_score_IForest_all-mpnet-base-v2",
          "context_dist_from_mean_embed_all-MiniLM-L6-v2",
          "context_outlier_score_ECOD_all-MiniLM-L6-v2",
          "context_outlier_score_IForest_all-MiniLM-L6-v2",
          "context_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "context_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "context_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],
        response: [
          "response_text_length",
          "response_num_words",
          "response_max_word_length",
          "response_avg_word_length",
          "response_perc_special_chars",
          "response_dist_from_mean_embed_all-mpnet-base-v2",
          "response_outlier_score_ECOD_all-mpnet-base-v2",
          "response_outlier_score_IForest_all-mpnet-base-v2",
          "response_dist_from_mean_embed_all-MiniLM-L6-v2",
          "response_outlier_score_ECOD_all-MiniLM-L6-v2",
          "response_outlier_score_IForest_all-MiniLM-L6-v2",
          "response_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "response_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "response_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],
      },
    },
  },
  opus: {
    name: "opus",
    filename: "opus100_en_es.parquet",
    metadata: {
      text_columns: ["en", "es"],
      other_columns: [],
      text_meta_columns: {
        en: [
          "en_text_length",
          "en_num_words",
          "en_max_word_length",
          "en_avg_word_length",
          "en_perc_special_chars",
          "en_dist_from_mean_embed_all-mpnet-base-v2",
          "en_outlier_score_ECOD_all-mpnet-base-v2",
          "en_outlier_score_IForest_all-mpnet-base-v2",
          "en_dist_from_mean_embed_all-MiniLM-L6-v2",
          "en_outlier_score_ECOD_all-MiniLM-L6-v2",
          "en_outlier_score_IForest_all-MiniLM-L6-v2",
          "en_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "en_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "en_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],
        es: [
          "es_text_length",
          "es_num_words",
          "es_max_word_length",
          "es_avg_word_length",
          "es_perc_special_chars",
          "es_dist_from_mean_embed_all-mpnet-base-v2",
          "es_outlier_score_ECOD_all-mpnet-base-v2",
          "es_outlier_score_IForest_all-mpnet-base-v2",
          "es_dist_from_mean_embed_all-MiniLM-L6-v2",
          "es_outlier_score_ECOD_all-MiniLM-L6-v2",
          "es_outlier_score_IForest_all-MiniLM-L6-v2",
          "es_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "es_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "es_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],
      },
    },
  },
  squad: {
    name: "squad",
    filename: "squad_validation.parquet",
    metadata: {
      text_columns: ["context", "question", "answers[0]"],
      other_columns: ["title"],
      text_meta_columns: {
        context: [
          "context_text_length",
          "context_num_words",
          "context_max_word_length",
          "context_avg_word_length",
          "context_perc_special_chars",
          "context_dist_from_mean_embed_all-mpnet-base-v2",
          "context_outlier_score_ECOD_all-mpnet-base-v2",
          "context_outlier_score_IForest_all-mpnet-base-v2",
          "context_dist_from_mean_embed_all-MiniLM-L6-v2",
          "context_outlier_score_ECOD_all-MiniLM-L6-v2",
          "context_outlier_score_IForest_all-MiniLM-L6-v2",
          "context_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "context_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "context_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],
        question: [
          "question_text_length",
          "question_num_words",
          "question_max_word_length",
          "question_avg_word_length",
          "question_perc_special_chars",
          "question_dist_from_mean_embed_all-mpnet-base-v2",
          "question_outlier_score_ECOD_all-mpnet-base-v2",
          "question_outlier_score_IForest_all-mpnet-base-v2",
          "question_dist_from_mean_embed_all-MiniLM-L6-v2",
          "question_outlier_score_ECOD_all-MiniLM-L6-v2",
          "question_outlier_score_IForest_all-MiniLM-L6-v2",
          "question_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "question_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "question_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],

        "answers[0]": [
          "answers[0]_text_length",
          "answers[0]_num_words",
          "answers[0]_max_word_length",
          "answers[0]_avg_word_length",
          "answers[0]_perc_special_chars",
          "answers[0]_dist_from_mean_embed_all-mpnet-base-v2",
          "answers[0]_outlier_score_ECOD_all-mpnet-base-v2",
          "answers[0]_outlier_score_IForest_all-mpnet-base-v2",
          "answers[0]_dist_from_mean_embed_all-MiniLM-L6-v2",
          "answers[0]_outlier_score_ECOD_all-MiniLM-L6-v2",
          "answers[0]_outlier_score_IForest_all-MiniLM-L6-v2",
          "answers[0]_dist_from_mean_embed_distiluse-base-multilingual-cased-v1",
          "answers[0]_outlier_score_ECOD_distiluse-base-multilingual-cased-v1",
          "answers[0]_outlier_score_IForest_distiluse-base-multilingual-cased-v1",
        ],
      },
    },
  },
  vast2021: {
    name: "vast2021",
    filename: "vast2021.parquet",
    metadata: {
      text_columns: ["message"],
      other_columns: [
        "type",
        "date(yyyyMMddHHmmss)",
        "author",
        "latitude",
        "longitude",
        "location",
        "date",
      ],
      text_meta_columns: {
        message: [
          "message_text_length",
          "message_num_words",
          "message_max_word_length",
          "message_avg_word_length",
          "message_perc_special_chars",
          "message_dist_from_mean_embed_all-mpnet-base-v2",
          "message_outlier_score_ECOD_all-mpnet-base-v2",
          "message_outlier_score_IForest_all-mpnet-base-v2",
        ],
      },
    },
  },
};
